import type { AdSlot, Advertiser, Campaign, Creative, Publisher, Session } from "../types";
interface Db { advertisers: Advertiser[]; campaigns: Campaign[]; creatives: Creative[]; publishers: Publisher[]; slots: AdSlot[]; }
const DB_KEY = "oas_mock_db_v1";
const seed = (): Db => ({
  advertisers: [{ id: 1, name: "Demo Advertiser", company: "Demo Company Inc.", contact_email: "ops@demo.com", balance: 10000, daily_budget: 500, status: 1 }, { id: 2, name: "Acme Games", company: "Acme Games Ltd.", contact_email: "growth@acme.games", balance: 4200, daily_budget: 250, status: 1 }],
  campaigns: [{ id: 1, advertiser_id: 1, name: "Summer Sale", description: "US/CA push", budget_daily: 100, budget_total: 1000, spent_today: 42.5, spent_total: 412, bid_type: 1, bid_amount: 5, freq_cap_daily: 10, freq_cap_hourly: 3, status: 1, impressions: 82400, clicks: 3110, conversions: 96 }, { id: 2, advertiser_id: 1, name: "App Install - Android", description: "CPI push", budget_daily: 60, budget_total: 600, spent_today: 61.2, spent_total: 305, bid_type: 2, bid_amount: 0.8, freq_cap_daily: 5, freq_cap_hourly: 2, status: 0, impressions: 51200, clicks: 2044, conversions: 61 }, { id: 3, advertiser_id: 2, name: "New Game Launch", description: "CPI campaign", budget_daily: 200, budget_total: 2000, spent_today: 87.4, spent_total: 640, bid_type: 2, bid_amount: 1.4, freq_cap_daily: 8, freq_cap_hourly: 3, status: 1, impressions: 120500, clicks: 5302, conversions: 210 }],
  creatives: [{ id: 1, campaign_id: 1, title: "Summer Sale - 50% Off!", description: "Limited time offer", image_url: "https://placehold.co/600x340/ffcb69/10231f?text=Summer+Sale", landing_url: "https://example.com/sale", creative_type: 1, width: 300, height: 250, status: 1, quality_score: 85 }, { id: 2, campaign_id: 1, title: "Free shipping this week", description: "On all orders", image_url: "https://placehold.co/600x340/8ec5a3/10231f?text=Free+Shipping", landing_url: "https://example.com/shipping", creative_type: 2, width: 300, height: 250, status: 1, quality_score: 78 }],
  publishers: [{ id: 1, name: "Demo Publisher", email: "ads@demopublisher.com", site_url: "https://demo-publisher.com", status: 1 }],
  slots: [{ id: 1, publisher_id: 1, slot_id: "banner_home_top", name: "Home Top Banner", format: 1, width: 300, height: 250, status: 1, ecpm_today: 4.21 }, { id: 2, publisher_id: 1, slot_id: "native_feed_1", name: "Feed Native #1", format: 2, width: 600, height: 300, status: 1, ecpm_today: 2.87 }],
});
const load = (): Db => { try { const raw = localStorage.getItem(DB_KEY); if (raw) return JSON.parse(raw) as Db; } catch { /* reseed */ } const db = seed(); save(db); return db; };
const save = (db: Db) => localStorage.setItem(DB_KEY, JSON.stringify(db));
const delay = (ms = 120) => new Promise<void>((resolve) => setTimeout(resolve, ms));
const nextId = (rows: { id: number }[]) => rows.length ? Math.max(...rows.map((row) => row.id)) + 1 : 1;
export async function mockLogin(email: string, password: string): Promise<Session> { await delay(); const users: Record<string, { password: string; session: Session }> = { "admin@openadserver.dev": { password: "admin123", session: { user: { id: "usr_admin", name: "Platform Admin", email, role: "admin" }, token: "demo-token-admin" } }, "advertiser@openadserver.dev": { password: "ad1234", session: { user: { id: "usr_adv", name: "Demo Advertiser", email, role: "advertiser" }, token: "demo-token-advertiser" } }, "publisher@openadserver.dev": { password: "pub1234", session: { user: { id: "usr_pub", name: "Demo Publisher", email, role: "publisher" }, token: "demo-token-publisher" } } }; const hit = users[email.trim().toLowerCase()]; if (!hit || hit.password !== password) throw new Error("Invalid email or password"); return hit.session; }
export async function listAdvertisers() { await delay(); return load().advertisers; }
export async function createAdvertiser(input: Omit<Advertiser, "id" | "status">) { await delay(); const db = load(); const row = { ...input, id: nextId(db.advertisers), status: 1 }; db.advertisers.push(row); save(db); return row; }
export async function setAdvertiserStatus(id: number, status: number) { await delay(); const db = load(); const row = db.advertisers.find((item) => item.id === id); if (row) row.status = status; save(db); }
export async function listCampaigns(advertiserId?: number) { await delay(); const rows = load().campaigns; return advertiserId ? rows.filter((row) => row.advertiser_id === advertiserId) : rows; }
export async function getCampaign(id: number) { await delay(); return load().campaigns.find((row) => row.id === id); }
export interface CampaignInput { name: string; description: string; budget_daily: number; budget_total: number; bid_type: number; bid_amount: number; freq_cap_daily: number; freq_cap_hourly: number; start_time?: string; end_time?: string; }
export async function createCampaign(advertiser_id: number, input: CampaignInput) { await delay(); const db = load(); const row: Campaign = { ...input, id: nextId(db.campaigns), advertiser_id, spent_today: 0, spent_total: 0, status: 1, impressions: 0, clicks: 0, conversions: 0 }; db.campaigns.push(row); save(db); return row; }
export async function setCampaignStatus(id: number, status: number) { await delay(); const db = load(); const row = db.campaigns.find((item) => item.id === id); if (row) row.status = status; save(db); }
export async function listCreatives(campaignId: number) { await delay(); return load().creatives.filter((row) => row.campaign_id === campaignId); }
export interface CreativeInput { title: string; description: string; image_url: string; landing_url: string; creative_type: number; width: number; height: number; }
export async function createCreative(campaign_id: number, input: CreativeInput) { await delay(); const db = load(); const row: Creative = { ...input, id: nextId(db.creatives), campaign_id, status: 1, quality_score: 80 }; db.creatives.push(row); save(db); return row; }
export async function listPublishers() { await delay(); return load().publishers; }
export async function createPublisher(input: Omit<Publisher, "id" | "status">) { await delay(); const db = load(); const row = { ...input, id: nextId(db.publishers), status: 1 }; db.publishers.push(row); save(db); return row; }
export async function listSlots(publisherId?: number) { await delay(); const rows = load().slots; return publisherId ? rows.filter((row) => row.publisher_id === publisherId) : rows; }
export async function createSlot(publisher_id: number, input: Omit<AdSlot, "id" | "publisher_id" | "status" | "ecpm_today">) { await delay(); const db = load(); const row = { ...input, id: nextId(db.slots), publisher_id, status: 1, ecpm_today: 0 }; db.slots.push(row); save(db); return row; }
